server:
  port: 7788
  servlet:
    context-path: /scala-java

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://master:3306/scalajava
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql